name: bloc_architecture
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.4.1
  flutter: 3.22.1

dependencies:
  bloc_architecture_core: any
  bloc_architecture_localization: any
  bloc_architecture_pagination: any
  bloc_architecture_widget: any
  bloc_concurrency: ^0.2.3
  dio: ^5.4.0
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  freezed_annotation: ^2.4.1
  get_it: ^7.6.7
  go_router: ^14.0.2
  hydrated_bloc: ^9.1.4
  infinite_scroll_pagination: ^4.0.0
  injectable: ^2.3.2
  intl: any
  json_annotation: ^4.9.0
  package_info_plus: ^8.0.0
  path_provider: ^2.1.2
  retrofit: ^4.0.3

dev_dependencies:
  build_runner: any
  build_verify: any
  flutter_gen_runner: any
  flutter_test:
    sdk: flutter
  freezed: any
  go_router_builder: any
  injectable_generator: any
  json_serializable: any
  retrofit_generator: any

dependency_overrides:
  bloc_architecture_core:
    path: ../bloc_architecture_core
  bloc_architecture_localization:
    path: ../bloc_architecture_localization
  bloc_architecture_pagination:
    path: ../bloc_architecture_pagination
  bloc_architecture_widget:
    path: ../bloc_architecture_widget

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          weight: 400

flutter_gen:
  output: lib/core/theme # Optional (default: lib/gen/)
  line_length: 120 # Optional (default: 80)
  integrations:
    flutter_svg: true
    lottie: false
  assets:
    enabled: true
    outputs:
      class_name: AppAssets
  fonts:
    enabled: true
    outputs:
      class_name: AppFonts
  colors:
    enabled: true
    outputs:
      class_name: AssetColors
    inputs:
      - assets/colors/colors.xml
