name: bloc_architecture_widget
description: "Widget for BLoC Architecture"
version: 0.0.1
homepage: https://github.com/development707/bloc_architecture
repository: https://github.com/development707/bloc_architecture/tree/main/bloc_architecture_widget

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bloc_architecture_core:
    # path: ../bloc_architecture_core
  bloc_architecture_localization:
    # path: ../bloc_architecture_localization
  flutter:
    sdk: flutter
  intl: any
