arb-dir: lib/l10n
output-dir: lib/generated
template-arb-file: bloc_architecture_en.arb
output-class: BlocArchitectureLocalizations
output-localization-file: bloc_architecture_localizations.dart
synthetic-package: false
