# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Check

on:
  pull_request:
    branches: ["main"]

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Check pull request title
        run: |
          if [[ ! $github.event.pull_request.title =~ ^(\[[A-Za-z]+\]\s)+.+$ ]]; then
            echo "The pull request title did not match the expected format. Please check rule in README.md"
            exit 1
          fi

      - name: Check branch name
        run: |
          if [[ ! $github.event.pull_request.head.ref =~ ^(hotfix|feature|test|build)\/.+$ ]]; then
            echo "The branch name did not match the expected format. Please check rule in README.md"
            exit 1
          fi

      - name: Check commit message
        run: |
          for commit in "${github.event.commits[@]}"; do
            if [[ ! $commit.message =~ ^(feat|fix|refactor|docs|test|ci|chore)\(\S+\)\:\s.+$ ]]; then
              echo "The commit message did not match the expected format. Please check rule in README.md"
              exit 1
            fi
          done

      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: example/pubspec.yaml

      - run: flutter pub get

      - run: flutter pub run build_runner build --delete-conflicting-outputs

      - run: flutter analyze

      - run: dart format --output=none --set-exit-if-changed .
