name: Release Deploy Web

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - example/lib/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: example/pubspec.yaml

      - run: flutter config --enable-web
        working-directory: example

      - run: flutter pub get
        working-directory: example

      - run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: example

      - run: flutter build web --base-href=/Flutter-Bloc-Architecture/  --dart-define-from-file=.dev.env
        working-directory: example

      - uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GHUB_TOKEN }}
          publish_dir: ./example/build/web
