name: Deploy to GitHub Pages

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - example/lib/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: example/pubspec.yaml

      - name: Enable Flutter Web
        run: flutter config --enable-web

      - name: Download Dependencies
        run: flutter pub get
        working-directory: example

      - name: Generating Files
        run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: example

      - name: Build
        run: flutter build web --base-href=/Flutter-Bloc-Architecture/  --dart-define-from-file=env-dev.env
        working-directory: example

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GHUB_TOKEN }}
          publish_dir: ./example/build/web
