name: Release Deploy Android

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - example/lib/**

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: example/pubspec.yaml

      - run: flutter config --enable-android
        working-directory: example

      - run: flutter pub get
        working-directory: example

      - run: flutter pub run build_runner build --delete-conflicting-outputs
        working-directory: example

      - run: flutter build apk --dart-define-from-file=env-dev.env
        working-directory: example

      - uses: actions/upload-artifact@v4
        with:
          name: apk
          path: example/build/app/outputs/flutter-apk/*.apk
